language: python
sudo: true 
dist: trusty
python:
  - "2.7"
  - "3.6"
cache: pip
install:
  - sudo apt-get install libatlas-base-dev
  - python -m pip install --upgrade pip
  - python setup.py install
script:
  - PYTHONPATH=xnmt/ python tests/xnmt-tests.py
