language: python
dist: trusty
python:
  - "2.7"
  - "3.6"
cache: pip
before_install:
  - sudo apt-get install libatlas-base-dev
  - python -m pip install --upgrade pip
  - python -m pip install Cython
install:
  - pip install -r requirements.txt
script: pytest
